name: Collect Metrics Daily

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Call Metrics Endpoint
        run: curl -X GET https://www.tracking.yws-event.com//collect-metrics
